version: '3.8'

services:
    mysql:
        image: mysql:8.0
        container_name: iwkz-mysql-db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
            MYSQL_DATABASE: ${DATABASE_NAME}
            MYSQL_USER: ${DATABASE_USERNAME}
            MYSQL_PASSWORD: ${DATABASE_PASSWORD}
        volumes:
            - strapi-data:/var/lib/mysql
        ports:
            - '3306:3306'
        networks:
            - strapi-net

volumes:
    strapi-data:

networks:
    strapi-net:
        driver: bridge
